Traceback (most recent call last):
  File "./energy_noise.py", line 337, in <module>
    file1 = open(str(N)+'_gates_list.txt', 'r')
IOError: [Errno 2] No such file or directory: '10_gates_list.txt'

real	0m0.294s
user	0m3.793s
sys	0m0.507s
